require("enderVim.remap")
require("enderVim.nvim-tree-config")
require("enderVim.lazy")
require("enderVim.config")
require("enderVim.autocmds")
require("enderVim.plugins.config.icons")
require("enderVim.lsp-config")
require("enderVim.angular")
